# numpy


n dimenstional array object




less memory,fast,convinient

In [ ]:
import numpy as np

In [2]:
a = np.array([1,2,4,8])

In [4]:
a[0]

1

In [7]:
a[3]

8

In [11]:
a = np.array ([[1,3,4],[23,56,78]])

In [9]:
a.ndim

2

# ndim use to print the dimenstion

In [12]:
a.itemsize

4

In [13]:
a.size

6

In [14]:
a.shape

(2, 3)

In [16]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [19]:
a = np.array ([[1,3,4],[23,56,78]])

In [20]:
a

array([[ 1,  3,  4],
       [23, 56, 78]])

In [21]:
a.shape

(2, 3)

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
l= range(5)

In [24]:
l

range(0, 5)

In [25]:
np.arange(1,5,2)

array([1, 3])

In [26]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [29]:
a.reshape(1,1)

ValueError: cannot reshape array of size 6 into shape (1,1)

In [30]:
a = np.array ([[1,3,4],[23,56,78]])

In [32]:
a.reshape(6,1)

array([[ 1],
       [ 3],
       [ 4],
       [23],
       [56],
       [78]])

In [33]:
a.ravel()

array([ 1,  3,  4, 23, 56, 78])

In [34]:
a


array([[ 1,  3,  4],
       [23, 56, 78]])

In [35]:
a.min()

1

In [36]:
a.max()

78

In [37]:
a.sum()

165

In [39]:
a.sum(axis=1)

array([  8, 157])

In [41]:
np.sqrt(a)

array([[1.        , 1.73205081, 2.        ],
       [4.79583152, 7.48331477, 8.83176087]])

In [46]:
c = np.array([[6,4],[8,9]])

In [52]:
d = np.array([[1,3],[4,8]])

In [53]:
a

array([[ 1,  3,  4],
       [23, 56, 78]])

In [54]:
d

array([[1, 3],
       [4, 8]])

In [55]:
c

array([[1, 3],
       [4, 8]])

In [57]:
 d+c

array([[ 2,  6],
       [ 8, 16]])

In [59]:
d/c

array([[1., 1.],
       [1., 1.]])

In [61]:
c-d

array([[0, 0],
       [0, 0]])

# slicing stacking and indexing with boolean arrays

# #indexing and slicing

In [64]:
n= [6,7,8]

In [66]:
n[0:2]

[6, 7]

In [67]:
n[-1]

8

In [70]:
a = np.array([6,4,8])

In [72]:
a[0:2]

array([6, 4])

In [73]:
c = np.array([[6,4,5],[8,9,5],[4,6,8]])

In [74]:
c

array([[6, 4],
       [8, 9],
       [4, 6]])

In [77]:
c[1,1]

9

In [79]:
c[0:2,1]

array([4, 9])

In [80]:
c = np.array([[6,4,5],[8,9,5],[4,6,8]])

In [81]:
c

array([[6, 4, 5],
       [8, 9, 5],
       [4, 6, 8]])

In [82]:
for row in c:
    print(row)

[6 4 5]
[8 9 5]
[4 6 8]


In [86]:
for value in c.flat:
    print(value)

6
4
5
8
9
5
4
6
8


# stacking together two array

In [87]:
a =np.arange(6).reshape(3,2)

In [88]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [90]:
b = np.arange(6,12).reshape(3,2)

In [91]:
b


array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

# vstack vertical

In [92]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

#  hstack horizontal

In [93]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [97]:
np.hsplit(a,1)

[array([[0, 1],
        [2, 3],
        [4, 5]])]

In [98]:
a= np.arange(30).reshape(2,15)

In [99]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [100]:
np.hsplit(a,1)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [101]:
np.hsplit(a,5)

[array([[ 0,  1,  2],
        [15, 16, 17]]),
 array([[ 3,  4,  5],
        [18, 19, 20]]),
 array([[ 6,  7,  8],
        [21, 22, 23]]),
 array([[ 9, 10, 11],
        [24, 25, 26]]),
 array([[12, 13, 14],
        [27, 28, 29]])]

In [102]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

# indexing with boolena array

In [104]:
a = np.arange (12).reshape(3,4)

In [105]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
b = a>4

In [107]:
b


array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [108]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [109]:
a[b]=-1

In [110]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

# save txt file

In [112]:
c = np.array([[6,4,5],[8,9,5],[4,6,8]],np.int32)

In [114]:
np.savetxt("test.txt",c)

In [118]:
y = np.loadtxt("test.txt")
print(y)

[[6. 4. 5.]
 [8. 9. 5.]
 [4. 6. 8.]]


# itarate numpy array using nditer

In [119]:
for row in c:
    print(row)

[6 4 5]
[8 9 5]
[4 6 8]


In [120]:
for value in c.flat:
    print(value)
    

6
4
5
8
9
5
4
6
8


In [121]:
#c order

for value in np.nditer(c,order = 'c') :
    print(value)

6
4
5
8
9
5
4
6
8


In [122]:
#forten order

In [126]:
for value in np.nditer(c,order = 'f',flags=['external_loop']) :
    print(value)

[6 8 4]
[4 9 6]
[5 5 8]


# modify values while iterating


In [128]:
for x in np.nditer(c,op_flags= ['readwrite']):
    x[...]=x*x

In [129]:
c

array([[36, 16, 25],
       [64, 81, 25],
       [16, 36, 64]])